name: CI-LYJ2
on:
  check_suite:
    types: [rerequested, completed]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: echo hello lyj
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
