name: CI-LYJ
on:
  push:
    branches:
    - master 
    paths:
    - src/*
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: echo hello lyj
    - run: npm -v
    - run: java -version
    - run: python -v
   

